[build]
command = "export NODE_OPTIONS=--max_old_space_size=8192 && rm -rf .next node_modules/.cache && pnpm run build"
publish = "/opt/build/repo/.next"

[template.environment]
OPENAI_API_KEY = "set your OpenAI API Key"
ACCESS_CODE = "set your password to protect your api key"
